theme: jekyll-theme-cayman
title: PiTree
description: By converting them to decision trees, PiTree toolkit makes any sophisticated ABR algorithms implementable within an HTML5-based player. 
show_downloads: true